
import type { LucideIcon } from 'lucide-react';
import {
  Utensils, Car, Gamepad2, Home, Zap, ShoppingBag, Stethoscope, BookOpen, Plane, Shapes, Palette, Briefcase,
  Pizza, Coffee, Bus, Shirt, Pill, University, Landmark, Settings, Trash2, Edit3, PlusCircle, ChevronDown, X, Star,
  FileText, Archive, Tags, PencilLine, ListChecks, AlertTriangle, DollarSign, CreditCard, Target, BarChartHorizontalBig,
  PiggyBank, Wallet, TrendingUp, Users, Activity, Anchor, Apple, Award, Axe, Baby, Backpack, Banana, Banknote,
  Bath, Beer, Bell, Bike, Binary, Bitcoin, Blinds, Bone, Book, Bookmark, Bot, Box, Brain, BrickWall,
  Building, BusFront, Cable, Cake, Calculator, CalendarDays, Camera, CandlestickChart, Candy, CheckCircle,
  ChevronLeft, ChevronRight, CircleDollarSign, CircuitBoard, Citrus, Clapperboard, Clipboard, Clock, Cloud,
  Code, Cog, Coins, Columns, Combine, Command, Compass, Component, Computer, Construction, Contact,
  Container, Contrast, Cookie, Copy, Copyright, CornerDownLeft, Crown, CupSoda, Database, Diamond,
  Dice5, Disc, DraftingCompass, Drama, Dribbble, Drill, Dumbbell, Ear, Eclipse, Eraser, ExternalLink,
  Eye, Facebook, Factory, Fan, Feather, FerrisWheel, Figma, FileArchive, FileAudio, FileBadge, FileCheck,
  FileCode, FileDigit, FileDown, FileEdit, FileHeart, FileImage, FileInput, FileJson, FileKey, FileLock,
  FileMinus, FileMusic, FileOutput, FilePlus, FileQuestion, FileScan, FileSearch, FileSpreadsheet, FileSymlink,
  FileTerminal, FileTextIcon, FileType, FileUp, FileVideo, FileVolume, FileWarning, FileX, Files, Film,
  Filter, Fingerprint, Flag, Flame, Flashlight, FlaskConical, FlaskRound, FlipHorizontal, FlipVertical,
  Flower, Folder, FolderArchive, FolderCheck, FolderClock, FolderClosed, FolderCog, FolderDot, FolderDown,
  FolderEdit, FolderGit, FolderGit2, FolderHeart, FolderInput, FolderKanban, FolderKey, FolderLock, FolderMinus,
  FolderOpen, FolderOpenDot, FolderOutput, FolderPlus, FolderRoot, FolderSearch, FolderSymlink, FolderSync,
  FolderTree, FolderUp, FolderX, Folders, Footprints, Forklift, FormInput, Forward, Frame,
  Frown, Fuel, FunctionSquare, GalleryHorizontal, GalleryThumbnails, GanttChart, Gauge, Gavel, Gem, Ghost,
  Gift, GitBranch, GitCommit, GitCompare, GitFork, GitMerge, GitPullRequest, GitPullRequestClosed, GitPullRequestDraft,
  Github, Gitlab, GlassWater, Globe, Goal, Grab, GraduationCap, Grape, Grid, Grip, Group, Hammer, Hand,
  HandCoins, HandHeart, HandHelping, HandMetal, HandPlatter, Handshake, HardDrive, HardHat, Hash, Haze,
  Heading, Heart, HelpCircle, Hexagon, Highlighter, History, Hotel, Hourglass, Image, Images, Import,
  Inbox, Indent, IndianRupee, Info, Inspect, Instagram, Italic, IterationCcw, IterationCw, JapaneseYen,
  Joystick, Kanban, Key, Keyboard, Lamp, LandmarkIcon, Languages, Laptop, Lasso, Laugh, Layers, LayoutDashboard,
  LayoutGrid, LayoutList, LayoutTemplate, Leaf, Library, LifeBuoy, Lightbulb, Link, Linkedin, List,
  ListFilter, ListMinus, ListOrdered, ListPlus, ListRestart, ListTodo, ListVideo, ListX, Loader, Locate,
  Lock, LogIn, LogOut, Lollipop, Luggage, Magnet, Mail, Mailbox, Mails, Map, MapPin, Martini, Maximize,
  Medal, Megaphone, Menu, MessageCircle, MessageSquare, Mic, Microscope, Microwave, Milestone, Milk,
  Minus, Monitor, Moon, MoreHorizontal, Mountain, Mouse, MousePointer, Move, Music, Navigation, Network,
  Newspaper, Nut, Octagon, Option, Orbit, Package, PaintBucket, Paintbrush, Palmtree, PanelBottom,
  PanelLeftIcon, PanelRight, PanelTop, Paperclip, Parentheses, ParkingCircle, PartyPopper, Pause, PcCase, Pen,
  PenTool, Percent, PersonStanding, Phone, PictureInPicture, Pilcrow, Pin, Pipette, PlaneLanding, PlaneTakeoff,
  Play, Plug, Pocket, Podcast, Pointer, PoundSterling, Power, Printer, Projector, Puzzle, QrCode, Quote,
  Rabbit, Radar, Radiation, Radio, RadioReceiver, RadioTower, Rat, Ratio, RatioIcon, Receipt, RectangleHorizontal,
  RectangleVertical, Recycle, Redo, RefreshCcw, RefreshCw, Refrigerator, Regex, RemoveFormatting, Repeat,
  Reply, ReplyAll, Replace, Rewind, Rocket, RockingChair, RotateCcw, RotateCw, Route, Router, Rows, Rss,
  Ruler, RussianRuble, Sailboat, Save, Scale, Scan, School, Scissors, ScreenShare, Scroll, Search, Send,
  SeparatorHorizontal, SeparatorVertical, Server, Share, Sheet, Shield, Ship, ShoppingBasket, Shovel, ShowerHead,
  Shrink, Shrub, Shuffle, Sigma, Signal, Siren, SkipBack, SkipForward, Skull, Slack, Slice,
  Sliders, Smartphone, Smile, Snowflake, Sofa, SortAsc, SortDesc, Sprout, Square, Stamp, StepBack,
  StepForward, Sticker, StickyNote, Store, StretchHorizontal, StretchVertical, Strikethrough, Subscript,
  Subtitles, Sun, Sunrise, Sunset, SwissFranc, SwitchCamera, Sword, Swords, Syringe, Table, Tablet, Tag,
  TargetIcon, Tent, Terminal, TestTube, TestTubes, Text, TextCursor, TextQuote, TextSelect, Thermometer, ThumbsDown,
  ThumbsUp, Ticket, Timer, ToggleLeft, ToggleRight, Tornado, Touchpad, TowerControl, ToyBrick, Tractor,
  Train, Trash, TreeDeciduous, TreePine, Trees, Trello, TrendingDown, Triangle, Trophy, Truck, Tv, Twitch,
  Twitter, Type, Underline, Undo, UnfoldHorizontal, UnfoldVertical, Unlink, Unlock, Unplug, Upload, Usb,
  User, UserCheck, UserCog, UserMinus, UserPlus, UserX, VenetianMask, Verified, Vibrate, Video, View,
  Voicemail, Volume, Volume1, Volume2, VolumeX, Vote, Wand, Warehouse, Waypoints, Webcam, Webhook,
  Wheat, Wifi, Wind, Wine, Workflow, WrapText, Wrench, Youtube, ZapOff, ZoomIn, ZoomOut, Torus
} from 'lucide-react';

export const iconMap: { [key: string]: LucideIcon } = {
  Utensils, Car, Gamepad2, Home, Zap, ShoppingBag, Stethoscope, BookOpen, Plane, Shapes, Palette, Briefcase,
  Pizza, Coffee, Bus, Shirt, Pill, University, Landmark: LandmarkIcon, Settings, Trash2, Edit3, PlusCircle, ChevronDown, X, Star,
  FileText, Archive, Tags, PencilLine, ListChecks, AlertTriangle, DollarSign, CreditCard, Target: TargetIcon, BarChartHorizontalBig,
  PiggyBank, Wallet, TrendingUp, Users, Activity, Anchor, Apple, Award, Axe, Baby, Backpack, Banana, Banknote,
  Bath, Beer, Bell, Bike, Binary, Bitcoin, Blinds, Bone, BookIcon: Book, Bookmark, Bot, Box, Brain, BrickWall,
  Building, BusFront, Cable, Cake, Calculator, CalendarDays, Camera, CandlestickChart, Candy, CheckCircle,
  ChevronLeft, ChevronRight, CircleDollarSign, CircuitBoard, Citrus, Clapperboard, Clipboard, Clock, Cloud,
  Code, Cog, Coins, Columns, Combine, Command, Compass, Component, Computer, Construction, Contact,
  Container, Contrast, Cookie, Copy, Copyright, CornerDownLeft, Crown, CupSoda, Database, Diamond,
  Dice5, Disc, DraftingCompass, Drama, Dribbble, Drill, Dumbbell, Ear, Eclipse, Eraser, ExternalLink,
  Eye, Facebook, Factory, Fan, Feather, FerrisWheel, Figma, FileArchive, FileAudio, FileBadge, FileCheck,
  FileCode, FileDigit, FileDown, FileEdit, FileHeart, FileImage, FileInput, FileJson, FileKey, FileLock,
  FileMinus, FileMusic, FileOutput, FilePlus, FileQuestion, FileScan, FileSearch, FileSpreadsheet, FileSymlink,
  FileTerminal, FileTextIcon, FileType, FileUp, FileVideo, FileVolume, FileWarning, FileX, Files, Film,
  Filter, Fingerprint, Flag, Flame, Flashlight, FlaskConical, FlaskRound, FlipHorizontal, FlipVertical,
  Flower, Folder, FolderArchive, FolderCheck, FolderClock, FolderClosed, FolderCog, FolderDot, FolderDown,
  FolderEdit, FolderGit, FolderGit2, FolderHeart, FolderInput, FolderKanban, FolderKey, FolderLock, FolderMinus,
  FolderOpen, FolderOpenDot, FolderOutput, FolderPlus, FolderRoot, FolderSearch, FolderSymlink, FolderSync,
  FolderTree, FolderUp, FolderX, Folders, Footprints, Forklift, FormInput, Forward, Frame,
  Frown, Fuel, FunctionSquare, GalleryHorizontal, GalleryThumbnails, GanttChart, Gauge, Gavel, Gem, Ghost,
  Gift, GitBranch, GitCommit, GitCompare, GitFork, GitMerge, GitPullRequest, GitPullRequestClosed, GitPullRequestDraft,
  Github, Gitlab, GlassWater, Globe, Goal, Grab, GraduationCap, Grape, Grid, Grip, Group, Hammer, Hand,
  HandCoins, HandHeart, HandHelping, HandMetal, HandPlatter, Handshake, HardDrive, HardHat, Hash, Haze,
  Heading, Heart, HelpCircle, Hexagon, Highlighter, History, Hotel, Hourglass, Image, Images, Import,
  Inbox, Indent, IndianRupee, Info, Inspect, Instagram, Italic, IterationCcw, IterationCw, JapaneseYen,
  Joystick, Kanban, Key, Keyboard, Lamp, Languages, Laptop, Lasso, Laugh, Layers, LayoutDashboard,
  LayoutGrid, LayoutList, LayoutTemplate, Leaf, Library, LifeBuoy, Lightbulb, Link, Linkedin, List,
  ListFilter, ListMinus, ListOrdered, ListPlus, ListRestart, ListTodo, ListVideo, ListX, Loader, Locate,
  Lock, LogIn, LogOut, Lollipop, Luggage, Magnet, Mail, Mailbox, Mails, Map, MapPin, Martini, Maximize,
  Medal, Megaphone, Menu, MessageCircle, MessageSquare, Mic, Microscope, Microwave, Milestone, Milk,
  Minus, Monitor, Moon, MoreHorizontal, Mountain, Mouse, MousePointer, Move, Music, Navigation, Network,
  Newspaper, Nut, Octagon, Option, Orbit, Package, PaintBucket, Paintbrush, Palmtree, PanelBottom,
  PanelLeft: PanelLeftIcon, PanelRight, PanelTop, Paperclip, Parentheses, ParkingCircle, PartyPopper, Pause, PcCase, Pen,
  PenTool, Percent, PersonStanding, Phone, PictureInPicture, Pilcrow, Pin, Pipette, PlaneLanding, PlaneTakeoff,
  Play, Plug, Pocket, Podcast, Pointer, PoundSterling, Power, Printer, Projector, Puzzle, QrCode, Quote,
  Rabbit, Radar, Radiation, Radio, RadioReceiver, RadioTower, Rat, Ratio: RatioIcon, Receipt, RectangleHorizontal,
  RectangleVertical, Recycle, Redo, RefreshCcw, RefreshCw, Refrigerator, Regex, RemoveFormatting, Repeat,
  Reply, ReplyAll, Replace, Rewind, Rocket, RockingChair, RotateCcw, RotateCw, Route, Router, Rows, Rss,
  Ruler, RussianRuble, Sailboat, Save, Scale, Scan, School, Scissors, ScreenShare, Scroll, Search, Send,
  SeparatorHorizontal, SeparatorVertical, Server, Share, Sheet, Shield, Ship, ShoppingBasket, Shovel, ShowerHead,
  Shrink, Shrub, Shuffle, Sigma, Signal, Siren, SkipBack, SkipForward, Skull, Slack, Slice,
  Sliders, Smartphone, Smile, Snowflake, Sofa, SortAsc, SortDesc, Sprout, Square, Stamp, StepBack,
  StepForward, Sticker, StickyNote, Store, StretchHorizontal, StretchVertical, Strikethrough, Subscript,
  Subtitles, Sun, Sunrise, Sunset, SwissFranc, SwitchCamera, Sword, Swords, Syringe, Table, Tablet, Tag,
  TargetIcon, Tent, Terminal, TestTube, TestTubes, Text, TextCursor, TextQuote, TextSelect, Thermometer, ThumbsDown,
  ThumbsUp, Ticket, Timer, ToggleLeft, ToggleRight, Tornado, Touchpad, TowerControl, ToyBrick, Tractor,
  Train, Trash, TreeDeciduous, TreePine, Trees, Trello, TrendingDown, Triangle, Trophy, Truck, Tv, Twitch,
  Twitter, Type, Underline, Undo, UnfoldHorizontal, UnfoldVertical, Unlink, Unlock, Unplug, Upload, Usb,
  User, UserCheck, UserCog, UserMinus, UserPlus, UserX, VenetianMask, Verified, Vibrate, Video, View,
  Voicemail, Volume, Volume1, Volume2, VolumeX, Vote, Wand, Warehouse, Waypoints, Webcam, Webhook,
  Wheat, Wifi, Wind, Wine, Workflow, WrapText, Wrench, Youtube, ZapOff, ZoomIn, ZoomOut, Torus
};

export type AvailableIconItem = {
  name: string;
  component: LucideIcon;
};

export const availableIcons: AvailableIconItem[] = Object.entries(iconMap)
  .map(([name, component]) => ({ name, component }))
  .sort((a, b) => a.name.localeCompare(b.name));

export const getDefaultIcon = () => Palette;
